// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartUpdateController from "./chart_update_controller"
application.register("chart-update", ChartUpdateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
